### ISSUE TITLE
Implement Logout path

### ISSUE THREAD

**Issue by Pymon** [mlinke-ai/kev.in#104]
Frontend needs a path to make the server delete the session cookie

**Comment by Looby72** [comment]
I could create a route on `/logout` to give the cookie an expiration time of 0 seconds. Then the client should remove the cookie instantly.

Then you could send an empty `POST` request to that route to logout as described above.

**Comment by mlinke-ai** [comment]
You could simply implement the `DELETE` method of the `login` route. The response returns an empty cookie (or a cookie where no token is set) and in the header we insert a redirect to the base URL.

**Comment by Looby72** [comment]
yeah, I'll do that.
