### ISSUE TITLE
Find a general type for the user_role / access level

### ISSUE THREAD

**Issue by Pymon** [mlinke-ai/kev.in#130]
Currently the backend sends a string for user_role for user api requests. To avoid unnecessary switch constructs in the frontend, it would be easier to use integers instead.

Access levels in the frontend are defined as following (sadmin to add):
```
export const accessLevels = {
    default: 0, // not logged  in
    user: 1,
    admin: 2,
    // (sadmin: 3)
};
```

**Comment by mlinke-ai** [comment]
I am currently working on a solution. See #126 for more.

Basically, everything we store as `enum` in the database, we return as both string (the field name ends with `_name`) and integer (ending in `_value`).
