### ISSUE TITLE
Backend could send user data in response to successful login

### ISSUE THREAD

**Issue by Pymon** [mlinke-ai/kev.in#162]
Currently the frontend has to send an additional user get request after each login, this could be avoided if the backend would send the user data in response for less data traffic

**Comment by Looby72** [comment]
Do you then still need the functionality to get the user data when sending an empty GET request to `/user`?

**Comment by Pymon** [comment]
Yes, this function is needed when the page is reloaded or the Tab or Browser were closed, to get user data again.
