### ISSUE TITLE
Please send proper HTTP status codes

### ISSUE THREAD

**Issue by Pymon** [mlinke-ai/kev.in#176]
I just wasted half of the night trying to implement error handling in the frontend. I kept getting type errors and thought my definitions were wrong. Very close to breaking out in tears I realized that it does not matter if the excercise that I requested existed or not. 
Currently backend responses are like: We have no data for you but everything is **OK**, here are empty lists and metadata without values which produce weird errors. 
Please send status codes that represent reality (for all routes), we need those to catch errors and keep sanity.

**Comment by mlinke-ai** [comment]
I have researched three solutions for this:
1. Simply check the `total` field in the meta data. If it is `0`, it means the list `data` is empty and your request yielded no results. That was one of my intentions why I introduced this field.
2. The back end could return a `404` error if the database query yields an empty selection. I have read about this solution on StackOverflow. However I am not a fan of this approach as I think a `404` error is a quite critical error and we should not overload it with a second meaning.
3. The back end could return a `204` status code. But in this case there will be no response body, which wouldn't be that big of a problem as `data` would be an empty list and `meta` would contain mostly `null` values.

**Comment by Pymon** [comment]
I see no need for any discussion that the server must not return `200 OK` if a requested resource is not available. 
1. Of course I could check for empty data fields, but I don't see the need of sending meta data at all if there is nothing to send. I think it is not very convenient to get `200` for all requests and than manually check the content for every different route.
2. On StackOverflow many people seem to think `404` is appropriate, but I consent to your opinion that `204` is the best solution here. That would also remove the unnecessary overhead of sending empty data and metadata as you said.

To clarify I didn't want to tell you which status codes to use, I just need more than `200` to catch errors reliably and efficiently. Sorry if my issue from yesterday was formulated inappropriate, I was really tired and sad about those status codes lying to my face all the time without me realizing. :smiling_face_with_tear:

**Comment by mlinke-ai** [comment]
No need to apologize, issues are for questions and problems.

I will implement the necessary checks ASAP.
