### ISSUE TITLE
Prepare project for presentation

### ISSUE THREAD

**Issue by Pymon** [mlinke-ai/kev.in#201]
- [x] create realistic exercise examples
- [x] remove dummy exercises

**Comment by Looby72** [comment]
Do you want us to pre define some exercise examples with working data?

At the moment our plan is to keep some dummy exercises for testing purposes. Therefor we want to create them only when we start the server in some sort of testing mode.

I could create an exercise for ParsonsPuzzle and programming exercise, just for the presentation.

To remove the creation of dummy exercises (and solutions) we can just comment out two lines in `server.py` around `line 30`:

```Python
#self._gen_exercises()
#self._gen_solutions()
```

**Comment by Looby72** [comment]
All dummy exercises from type `ParsonsPuzzleExercise` and `ProgrammingExercise ` should also work by now (they have real `exercise_content` and `exercise_solution`)

**Comment by Pymon** [comment]
Yeah I know that the dummy exercises work, but they are dummies, I thought we could pause generating them for the presentation and create a realistic example for each implemented exercise
