### ISSUE TITLE
frontend/static directory is missing

### ISSUE THREAD

**Issue by Looby72** [mlinke-ai/kev.in#40]
npm install in the current develop branch gives me this error:

```
> frontend@0.0.0 prepare
> npm run smui-theme-light && npm run smui-theme-dark


> frontend@0.0.0 smui-theme-light
> smui-theme compile src/static/smui.css -i src/themes

It looks like the output directory doesn't exist.
 src/static
```
maybe its cause the folder is in .gitignore?

**Comment by Looby72** [comment]
maybe [this](https://stackoverflow.com/questions/115983/how-do-i-add-an-empty-directory-to-a-git-repository) could help

**Comment by Pymon** [comment]
`frontend/static` is now ignored, folder stays in the structure
