### ISSUE TITLE
Authentication should work with email address

### ISSUE THREAD

**Issue by Pymon** [mlinke-ai/kev.in#48]
Because the username is  possibly not always unambiguously, authentication should use their email addresses to authenticate users.

**Comment by Looby72** [comment]
We cannot create users with the same username.

Therefor see the code in `backend/lib/routes/user.py on line 163` (in the develop Branch):

```Python
# if the selection contains an element we can't create a new one as would create a duplicate
result = dict(message="A user with this name already exists")
return make_response((jsonify(result)), 409)
```

A documentation for this method is not available yet, but under construction.

**Comment by Pymon** [comment]
Sorry, didn't see this.
