### ISSUE TITLE
authorize in exercise endpoint does not work

### ISSUE THREAD

**Issue by Looby72** [mlinke-ai/kev.in#74]
The `_authorize` functions in the user and in the exercise endpoint are not working anymore, since the Database model for the `user` table has been reworked. These `_authorize` functions currently try to get the `user_admin` attribute, which is not existing anymore.

**Comment by mlinke-ai** [comment]
The `_authorize` function should get the admin status out of the JWT token, not from the request arguments.

Also, we should move this function into `utils.py` inside the `core` directory. It would reduce redundancy and we would have only one function to maintain.

**Comment by Looby72** [comment]
I see only the _authorize in the exercise endpoint does not work at the moment because it checks in the database if the request client is an admin or not. Therefor it is using the old `user_admin` attribute and. not the new `user_role`. We could change that in a minor commit, or when we put all the authorize functions into one.
