### ISSUE TITLE
JS-fetch: GET does not work with HTTP-body

### ISSUE THREAD

**Issue by Looby72** [mlinke-ai/kev.in#89]
the fetch method does not support passing data through the body of a GET request, so the backend must ensure that it is possible to pass the data as URL-argument.
We also have to change that in the documentation.

**Comment by mlinke-ai** [comment]
Apparently, JavaScript has a URL datatype (`var url = new URL();`) which has a method `url.searchParams.append(KEY, VALUE);`. This method constructs an URL in the style of `/path?KEY=VALUE&KEY=VALUE`.

This makes my fear of having to manipulate a string in JavaScript irrelevant.

The frontend team might want to look into this.

**Comment by scrap111** [comment]
ahh i see thx
