### ISSUE TITLE
Demoting an admin to user does not work

### ISSUE THREAD

**Issue by mlinke-ai** [mlinke-ai/kev.in#99]
When trying to set the `user_role` of an admin to `3` (User), the server raises a ValueError and returns HTTP status 500.

The problem lies within [those](https://github.com/mlinke-ai/kev_in/blob/3f063ab078350d29d292bbfb850994ba361db309/backend/lib/core/utils.py#L45-L46) two lines.

I think raising errors is not a good idea. Code 500 should be used exclusively for runtime problems. We should not raise our own errors but handle the condition. Most cases we can handle before the `authorize` function gets called.

**Comment by Looby72** [comment]
Yeah this line is wrong and should be 
```Python
if method == 'PUT' and endpoint == 'user' and changeToAdmin == None:
```
I guess that fixes the issue.
I raised this Errors just that we know when the function is called in a wrong way (mainly for testing purposes). I can change that to other errors
